server:
  port: 8080

spring:
  application:
    name: immobi-market-web-app
  datasource:
    url: jdbc:postgresql://localhost:5432/test2
    username: spring
    password: spring
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true




