server:
  port: 8080

spring:
  application:
    name: immobi-market-web-app
  datasource:
    url: jdbc:postgresql://localhost:5432/immobi_market
    username: spring
    password: spring
    driver-class-name: org.postgresql.Driver


  mail:
    host: smtp.gmail.com
    port: 587
    username: empire.digiprem@gmail.com
    password: kakonana
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true





  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true

jwt:
  secret-key: Application de test
  expiration: (5*60*1000)

springdoc:
  model-converters:
      generic-models: empire.digiprem.models.ApiResponse




