server:
  port: 8090

spring:
  application:
    name: immobi-market-web-app
  datasource:
    url: jdbc:postgresql://localhost:5432/immobi_market
    username: spring
    password: spring
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.monprojet: TRACE

  mail:
    host: smtp.gmail.com
    port: 587
    username: empire.digiprem@gmail.com
    password: kakonana
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: false

jwt:
  secret-key: Application de test
  expiration: (5*60*1000)

springdoc:
  model-converters:
      generic-models: empire.digiprem.models.ApiResponse




